spring.application.name=user-service
spring.config.import=classpath:user-policy.yml

# Database URL, Username, and Password
spring.datasource.url=jdbc:postgresql://localhost:5432/userServiceDB
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
